spring.application.name=GenAI
server.port=9090
spring.config.import=optional:application-local.properties
logging.level.com.openai=DEBUG
logging.level.okhttp3=DEBUG

weather.api-key=cb408b035370894d3e88c06854db93a3
currency-exchange.api-key=ba41e17b6593c2933ee162e5