spring.application.name=GenAI
server.port=9090
google_api.key=AIzaSyBOiDRdP_mwymcPQLndBju_4ET2ZM37ogQ
spring.ai.openai.chat.model=gpt-5.6-luna
spring.ai.openai.api-key=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
